//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOR_Launcher {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ru_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ru_RU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GOR_Launcher.ru_RU", typeof(ru_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительный контент.
        /// </summary>
        internal static string additionalfiles_header {
            get {
                return ResourceManager.GetString("additionalfiles_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка.
        /// </summary>
        internal static string downloading {
            get {
                return ResourceManager.GetString("downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игровые файлы актуальной версии!.
        /// </summary>
        internal static string fileDone {
            get {
                return ResourceManager.GetString("fileDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверка.
        /// </summary>
        internal static string fileValidating {
            get {
                return ResourceManager.GetString("fileValidating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Никнейм.
        /// </summary>
        internal static string nicknameInput {
            get {
                return ResourceManager.GetString("nicknameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игроков онлайн:.
        /// </summary>
        internal static string onlinePlayers {
            get {
                return ResourceManager.GetString("onlinePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Играть.
        /// </summary>
        internal static string playButton {
            get {
                return ResourceManager.GetString("playButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string settings_header {
            get {
                return ResourceManager.GetString("settings_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык:.
        /// </summary>
        internal static string settings_language {
            get {
                return ResourceManager.GetString("settings_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Громкость музыки:.
        /// </summary>
        internal static string settings_musvolume {
            get {
                return ResourceManager.GetString("settings_musvolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрешение экрана:.
        /// </summary>
        internal static string settings_resolution {
            get {
                return ResourceManager.GetString("settings_resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чувствительность мыши:.
        /// </summary>
        internal static string settings_sensitivity {
            get {
                return ResourceManager.GetString("settings_sensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Громкость звуков:.
        /// </summary>
        internal static string settings_sndvolume {
            get {
                return ResourceManager.GetString("settings_sndvolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЗАПУСТИТЬ ПРОВЕРКУ ФАЙЛОВ.
        /// </summary>
        internal static string settings_validation {
            get {
                return ResourceManager.GetString("settings_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оконный режим:.
        /// </summary>
        internal static string settings_windowed {
            get {
                return ResourceManager.GetString("settings_windowed", resourceCulture);
            }
        }
    }
}
