//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GOR_Launcher {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ru_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ru_RU() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GOR_Launcher.ru_RU", typeof(ru_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительный контент.
        /// </summary>
        internal static string additionalfiles_header {
            get {
                return ResourceManager.GetString("additionalfiles_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка.
        /// </summary>
        internal static string downloading {
            get {
                return ResourceManager.GetString("downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игровые файлы актуальной версии!.
        /// </summary>
        internal static string fileDone {
            get {
                return ResourceManager.GetString("fileDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверка.
        /// </summary>
        internal static string fileValidating {
            get {
                return ResourceManager.GetString("fileValidating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Никнейм.
        /// </summary>
        internal static string nicknameInput {
            get {
                return ResourceManager.GetString("nicknameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В игре:.
        /// </summary>
        internal static string onlinePlayers {
            get {
                return ResourceManager.GetString("onlinePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В игру.
        /// </summary>
        internal static string playButton {
            get {
                return ResourceManager.GetString("playButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервер недоступен.
        /// </summary>
        internal static string serverStatusOffline {
            get {
                return ResourceManager.GetString("serverStatusOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервер включен.
        /// </summary>
        internal static string serverStatusReady {
            get {
                return ResourceManager.GetString("serverStatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Альтернативное подключение:.
        /// </summary>
        internal static string settings_altConnection {
            get {
                return ResourceManager.GetString("settings_altConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        internal static string settings_header {
            get {
                return ResourceManager.GetString("settings_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык:.
        /// </summary>
        internal static string settings_language {
            get {
                return ResourceManager.GetString("settings_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Музыка:.
        /// </summary>
        internal static string settings_musvolume {
            get {
                return ResourceManager.GetString("settings_musvolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разрешение:.
        /// </summary>
        internal static string settings_resolution {
            get {
                return ResourceManager.GetString("settings_resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чувствительность:.
        /// </summary>
        internal static string settings_sensitivity {
            get {
                return ResourceManager.GetString("settings_sensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Звук:.
        /// </summary>
        internal static string settings_sndvolume {
            get {
                return ResourceManager.GetString("settings_sndvolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЗАПУСТИТЬ ПРОВЕРКУ ФАЙЛОВ.
        /// </summary>
        internal static string settings_validation {
            get {
                return ResourceManager.GetString("settings_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оконный режим:.
        /// </summary>
        internal static string settings_windowed {
            get {
                return ResourceManager.GetString("settings_windowed", resourceCulture);
            }
        }
    }
}
